apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-fastapi
  template:
    metadata:
      labels:
        app: azure-fastapi
    spec:
      containers:
      - name: azure-fastapi
        image: nsdr1228/azure-fastapi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: azure-fastapi 
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: azure-fastapi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: azure-fastapi
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: aks-helloworld.029881ab04f646e78645.southcentralus.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: azure-fastapi
            port: 
              number: 80
